# Generated by Django 4.2.3 on 2024-03-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sector',
            field=models.CharField(default='Undefined', max_length=256),
        ),
    ]
